name: CI/CD Pipeline - CTI Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      #  Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      #  Installer Docker Buildx
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #  Build toutes les images Docker
      - name: Build Docker images
        run: docker-compose -f docker-compose.yml build --pull

      #  Push images sur DockerHub (optionnel)
      - name: Push Docker images
        run: |
          docker-compose -f docker-compose.yml push || echo "Skipping push if not needed"

      #  Déployer sur VPS via SSH
     # - name: Deploy to VPS
      #  uses: appleboy/ssh-action@v0.1.9
        #with:
          #host: ${{ secrets.VPS_HOST }}
          #username: ${{ secrets.VPS_USER }}
          #key: ${{ secrets.VPS_SSH_KEY }}
          #script: |
           # cd /home/devops/cti-project || mkdir -p /home/devops/cti-project
          #  git pull origin main
            #docker-compose -f docker-compose.yml down
            #docker-compose -f docker-compose.yml up -d --build
